with 

source as (

    select * from {{ source('banking', 'fdic_rc') }}

),

renamed as (

    select
        idrssd AS bank_id,
        {{ banking_date('report_date') }} as report_date,
        rcon3230 AS common_stock,
        rcon3838 AS perpetual_preferred_stock_and_related_surplus,
        rcfd3548 AS trading_liabilities_total,
        rcfd0426 AS other_identifiable_intangible_assets,
        rcfd2948 AS total_liabilities_and_minority_interest,
        rcfd1773 AS available_for_sale_debt_securities,
        rcon3190 AS other_borrowed_money,
        rconb529 AS loans_and_leases_net_of_unearned_income_and_allowance,
        rcfd3123 AS allowance_for_credit_losses_on_loan_and_lease,
        rcfd3545 AS trading_assets_total,
        rconb993 AS federal_funds_purchased_in_domestic_offices,
        rconb528 AS loans_and_leases_net_of_unearned_income_totals,
        rcon2200 AS total_deposits,
        rcfd0071 AS interest_bearing_balances,
        rcfd2155 AS customers_liability_to_this_bank_on_acceptances_outstanding,
        rcon5369 AS loans_and_leases_held_for_sale,
        rcfd6724 AS audit_indicator,
        rconja22 AS equity_sec_with_readily_determinable_fair_values,
        rcon2930 AS other_liabilities_total,
        rcon8678 AS fiscal_year_end_date,
        rcfd2130 AS investments_and_unconsolidated_subsidiaries_and_associated_companies,
        rcon1350 AS federal_funds_sold_and_securities_purchased_under_agreements_to_resell,
        rcon2150 AS other_real_estate_owned,
        rcfdb528 AS loans_and_leases_net_of_unearned_income_totals,
        rcfd3632 AS undivided_profits_and_capital_reserves,
        rconb989 AS securities_purchased_under_agreements_to_resell,
        rcon2160 AS other_assets,
        rcfd1754 AS held_to_maturity_securities_total,
        rcfd3210 AS total_equity_capital,
        rcon3839 AS surplus,
        rcon1754 AS held_to_maturity_securities_total,
        rcon2948 AS total_liabilities_and_minority_interest,
        rcon2130 AS investments_and_unconsolidated_subsidiaries_and_associated_companies,
        rcfd2143 AS intangible_assets,
        rcfd3300 AS total_liabilities_limited_life_preferred_stock_and_equity_capital,
        rcfd3656 AS direct_and_indirect_investments_in_real_estate_ventures,
        rcon6636 AS total_interest_bearing_deposits_in_foreign_and_domestic_offices,
        rcon6724 AS audit_indicator,
        rcong105 AS total_equity_capital_including_noncontrolling_minority_interests,
        rcfdg105 AS total_equity_capital_including_noncontrolling_minority_interests_in_consoli,
        rcfn2200 AS total_deposits,
        rcfdb989 AS securities_purchased_under_agreements_to_resell,
        rcfn6631 AS deposits_noninterest_bearing,
        rcfda130 AS other_components_of_equity_capital,
        rcon2155 AS customers_liability_to_this_bank_on_acceptances_outstanding,
        rcon3163 AS goodwill,
        rconb987 AS federal_funds_sold,
        rcfdb529 AS loans_and_leases_net_of_unearned_income_and_allowance,
        rcfdb995 AS securities_sold_under_agreements_to_repurchase,
        rcfdja22 AS equity_sec_with_readily_determinable_fair_values_not_held_for_trading,
        rcon3200 AS subordinated_notes_and_debentures,
        rcon3300 AS total_liabilities_limited_life_preferred_stock_and_equity_capital,
        rconb995 AS securities_sold_under_agreements_to_repurchase,
        rcon2143 AS intangible_assets,
        rcon3210 AS total_equity_capital,
        rcfdjj34 AS held_to_maturity_securities,
        rcon2145 AS premises_and_fixed_assets,
        rcfd3000 AS minority_interest_in_consolidated_subsidiaries_and_similar_items,
        rcfd2145 AS premises_and_fixed_assets,
        rcfd3163 AS goodwill,
        rcon6631 AS deposits_noninterest_bearing,
        rcona130 AS other_components_of_equity_capital,
        rcfd5369 AS loans_and_leases_held_for_sale,
        rcon2920 AS banks_liability_on_acceptances,
        rconjj34 AS held_to_maturity_securities,
        rcon3656 AS direct_and_indirect_investments_in_real_estate_ventures,
        rcfd2150 AS other_real_estate_owned_2,
        rcon2170 AS total_assets,
        rcfd1350 AS federal_funds_sold_and_securities_purchased_under_agreements_to_resell_in_d,
        rconb530 AS accumulated_other_comprehensive_income,
        rcfd3838 AS perpetual_preferred_stock_and_related_surplus,
        rcfd2160 AS other_assets_2,
        rcfd3190 AS other_borrowed_money,
        rcon0081 AS noninterest_bearing_balances_and_currency_and_coin,
        rcon3000 AS minority_interest_in_consolidated_subsidiaries_and_similar_items,
        rcfd0081 AS noninterest_bearing_balances_and_currency_and_coin,
        rcon0071 AS interest_bearing_balances,
        rcfd2930 AS other_liabilities_total,
        rcon1773 AS available_for_sale_debt_securities_from_schedule_rc_b_column_d,
        rcfd3839 AS surplus,
        rcfd2920 AS bank_s_liability_on_acceptances_executed_and_outstanding,
        rcon3123 AS allowance_for_credit_losses_on_loan_and_lease,
        rcfdb530 AS accumulated_other_comprehensive_income,
        rcfn6636 AS total_interest_bearing_deposits_in_foreign_and_domestic_offices,
        rcfd2800 AS federal_funds_purchased_and_securities_sold_under_agreements_to_repurchase,
        rcon2800 AS federal_funds_purchased_and_securities_sold_under_agreements_to_repurchase,
        rcon3545 AS trading_assets_total,
        rcfd3200 AS subordinated_notes_and_debentures,
        rcon3632 AS undivided_profits_and_capital_reserves

    from source

)

select * from renamed
