with 

source as (

    select * from {{ source('gates', 'iceberg_v_investment__c') }}

),

renamed as (

    select
        lastmodifieddate as last_modified_date,
        lastreferenceddate as last_referenced_date,
        lastvieweddate as last_viewed_date,
        legacy_investment_id__c as legacy_investment_id,
        legal_entity__c as legal_entity,
        managing_team__c as managing_team,
        name,
        opportunity_contractrequest_id__c as opportunity_contract_request_id,
        ownerid as owner_id,
        package_contract_id__c as package_contract_id,
        parent_investment__c as parent_investment,
        primary_contact__c as primary_contact,
        process_as_straightforward__c as process_as_straightforward,
        record_type__c as record_type,
        recordtypeid as record_type_id,
        signed_date__c as signed_date,
        start_date__c as start_date,
        status__c as status,
        straightforward__c as straightforward,
        straightforward_investment__c as straightforward_investment,
        subtype__c as subtype,
        supporting_team__c as supporting_team,
        systemmodstamp as system_mod_stamp,
        taxes__c as taxes,
        total_amount_expended__c as total_amount_expended,
        type__c as type,
        workflow_step__c as workflow_step,
        workflow_step_automation__c as workflow_step_automation,
        workflow_step_number__c as workflow_step_number,
        show_in_reporting__c as show_in_reporting,
        secondary_investment_owner__c as secondary_investment_owner,
        benefiting_entity__c as benefiting_entity,
        confidential_agreement__c as confidential_agreement,
        vendor_paper__c as vendor_paper,
        end_date_type__c as end_date_type,
        payment_entity__c as payment_entity,
        feature_enabled__c as feature_enabled,
        amendment_completed_date__c as amendment_completed_date,
        innovative_finance_investment__c as innovative_finance_investment,
        interest_received_proceed_amount__c as interest_received_proceed_amount,
        realized_gain_loss_amount__c as realized_gain_loss_amount,
        return_principal_amount__c as return_principal_amount,
        straightforward_state__c as straightforward_state,
        investment_variant__c as investment_variant,
        gender_integration_category__c as gender_integration_category,
        parent_investment_id__c as parent_investment_id,
        investment_amount_subject_to_er__c as investment_amount_subject_to_er,
        no_maximum_budget__c as no_maximum_budget,
        parent_amendment__c as parent_amendment,
        agreement_type__c as agreement_type,
        amendment_amount__c as amendment_amount,
        amendment_amount_approved__c as amendment_amount_approved,
        amendment_effective_date__c as amendment_effective_date,
        amendment_id__c as amendment_id,
        amendment_increment__c as amendment_increment,
        amendment_new_final_report_due_date__c as amendment_new_final_report_due_date,
        amendment_number__c as amendment_number,
        amendment_type__c as amendment_type,
        amendment_ui_components__c as amendment_ui_components,
        application_version__c as application_version,
        approved_date__c as approved_date,
        authorized_external_signer__c as authorized_external_signer,
        closed_date__c as closed_date,
        committed_date__c as committed_date,
        compensation_and_fees__c as compensation_and_fees,
        createdbyid as created_by_id,
        createddate as created_date,
        currencyisocode as currency_iso_code,
        description__c as description,
        duration_months__c as duration_months,
        end_date__c as end_date,
        er_status_confirmed__c as er_status_confirmed,
        er_status_confirmed_by__c as er_status_confirmed_by,
        er_status_confirmed_date__c as er_status_confirmed_date,
        expenses__c as expenses,
        fiscal_agent_count__c as fiscal_agent_count,
        forecasted_approval_date__c as forecasted_approval_date,
        generate_agreement_url__c as generate_agreement_url,
        grantee_vendor__c as grantee_vendor,
        id,
        investment_amount__c as investment_amount,
        investment_amount_approved__c as investment_amount_approved,
        investment_amount_outstanding__c as investment_amount_outstanding,
        investment_amount_paid__c as investment_amount_paid,
        investment_amount_unscheduled__c as investment_amount_unscheduled,
        investment_brief__c as investment_brief,
        investment_compliance__c as investment_compliance,
        investment_coordinator__c as investment_coordinator,
        investment_diligence__c as investment_diligence,
        investment_external_id__c as investment_external_id,
        investment_number__c as investment_number,
        investment_owner__c as investment_owner,
        investment_range_high__c as investment_range_high,
        investment_range_low__c as investment_range_low,
        isdeleted as is_deleted,
        lastactivitydate as last_activity_date,
        lastmodifiedbyid as last_modified_by_id

    from source

)

select * from renamed
