name: Trigger DBT Cloud Job

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main

jobs:
  trigger-dbt-job:
    runs-on: ubuntu-latest
    
    env:
      JOB_ID: 567183
      DBT_CLOUD_ACCOUNT_ID: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
      DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: yezz123/setup-uv@v4
    - name: Install dbtc
      run: |
        uv pip install dbtc
      env:
        UV_SYSTEM_PYTHON: 1

    - name: Trigger DBT Cloud Job
      run: |
        # Assign response to run variable
        run=$(dbtc jobs trigger --job-id $JOB_ID --payload '{"cause": "Triggered by GitHub Action"}')
        
        # Extract the is_success value using jq
        is_success=$(echo "$output" | jq -r '.data.is_success')
        
        # Print the output for debugging
        echo "DBT Cloud Job Output:"
        echo "$run"
        
        # Check if is_success is true
        if [ "$is_success" = "true" ]; then
          echo "Job was successful"
          exit 0
        else
          echo "Job failed"
          exit 1
        fi