name: Trigger DBT Cloud Job

on:
  pull_request:
    branches:
      - main

jobs:
  trigger-dbt-job:
    runs-on: ubuntu-latest
    
    env:
      JOB_ID: 567183
      DBT_CLOUD_ACCOUNT_ID: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
      DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: yezz123/setup-uv@v4
    - name: Install dbtc
      run: |
        uv pip install dbtc
      env:
        UV_SYSTEM_PYTHON: 1

    - name: Trigger DBT Cloud Job
      run: |
        dbtc trigger-job --job-id $JOB_ID --payload '{"cause": "Triggered by GitHub Action"}'
